# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DeepConverse-Sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DeepConverse-Sample
	pod 'DeepConverse', :path => "../DeepConverse"

  target 'DeepConverse-SampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DeepConverse-SampleUITests' do
    # Pods for testing
  end

end
